[CUMMINS]
Host = 
Username = admin
Password = cummins
TimeSyncMin = 10

[MQTT]
Host = localhost
Port = 1883
Username = 
Password = 
Prefix = cummins/
DeviceName = Cummins Generator
DiscoveryPrefix = homeassistant

[LOGGING]
# LogLevel = INFO
# Options: DEBUG, INFO, WARNING, ERROR
